package com.flea.pojo;

public class GoodsInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_goods_info.goods_id
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_goods_info.id
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_goods_info.user_id
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_goods_info.category
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_goods_info.is_outside
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    private Integer isOutside;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_goods_info.outside_status
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    private Integer outsideStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_goods_info.browser_number
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    private Long browserNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_goods_info.good_position_latitude
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    private Double goodPositionLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_goods_info.good_position_longitude
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    private Double goodPositionLongitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_goods_info.goods_id
     *
     * @return the value of flea_goods_info.goods_id
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_goods_info.goods_id
     *
     * @param goodsId the value for flea_goods_info.goods_id
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_goods_info.id
     *
     * @return the value of flea_goods_info.id
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_goods_info.id
     *
     * @param id the value for flea_goods_info.id
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_goods_info.user_id
     *
     * @return the value of flea_goods_info.user_id
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_goods_info.user_id
     *
     * @param userId the value for flea_goods_info.user_id
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_goods_info.category
     *
     * @return the value of flea_goods_info.category
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_goods_info.category
     *
     * @param category the value for flea_goods_info.category
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_goods_info.is_outside
     *
     * @return the value of flea_goods_info.is_outside
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public Integer getIsOutside() {
        return isOutside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_goods_info.is_outside
     *
     * @param isOutside the value for flea_goods_info.is_outside
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public void setIsOutside(Integer isOutside) {
        this.isOutside = isOutside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_goods_info.outside_status
     *
     * @return the value of flea_goods_info.outside_status
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public Integer getOutsideStatus() {
        return outsideStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_goods_info.outside_status
     *
     * @param outsideStatus the value for flea_goods_info.outside_status
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public void setOutsideStatus(Integer outsideStatus) {
        this.outsideStatus = outsideStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_goods_info.browser_number
     *
     * @return the value of flea_goods_info.browser_number
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public Long getBrowserNumber() {
        return browserNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_goods_info.browser_number
     *
     * @param browserNumber the value for flea_goods_info.browser_number
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public void setBrowserNumber(Long browserNumber) {
        this.browserNumber = browserNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_goods_info.good_position_latitude
     *
     * @return the value of flea_goods_info.good_position_latitude
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public Double getGoodPositionLatitude() {
        return goodPositionLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_goods_info.good_position_latitude
     *
     * @param goodPositionLatitude the value for flea_goods_info.good_position_latitude
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public void setGoodPositionLatitude(Double goodPositionLatitude) {
        this.goodPositionLatitude = goodPositionLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_goods_info.good_position_longitude
     *
     * @return the value of flea_goods_info.good_position_longitude
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public Double getGoodPositionLongitude() {
        return goodPositionLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_goods_info.good_position_longitude
     *
     * @param goodPositionLongitude the value for flea_goods_info.good_position_longitude
     *
     * @mbg.generated Sat Mar 30 18:13:01 CST 2019
     */
    public void setGoodPositionLongitude(Double goodPositionLongitude) {
        this.goodPositionLongitude = goodPositionLongitude;
    }
}