package com.flea.pojo;

import java.util.Date;

public class UserOriginalInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_user_original.user_id
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_user_original.id
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_user_original.phone_number
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_user_original.password
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_user_original.is_student
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    private Integer isStudent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_user_original.create_time
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_user_original.update_time
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flea_user_original.status
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_user_original.user_id
     *
     * @return the value of flea_user_original.user_id
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_user_original.user_id
     *
     * @param userId the value for flea_user_original.user_id
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_user_original.id
     *
     * @return the value of flea_user_original.id
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_user_original.id
     *
     * @param id the value for flea_user_original.id
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_user_original.phone_number
     *
     * @return the value of flea_user_original.phone_number
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_user_original.phone_number
     *
     * @param phoneNumber the value for flea_user_original.phone_number
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_user_original.password
     *
     * @return the value of flea_user_original.password
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_user_original.password
     *
     * @param password the value for flea_user_original.password
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_user_original.is_student
     *
     * @return the value of flea_user_original.is_student
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public Integer getIsStudent() {
        return isStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_user_original.is_student
     *
     * @param isStudent the value for flea_user_original.is_student
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public void setIsStudent(Integer isStudent) {
        this.isStudent = isStudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_user_original.create_time
     *
     * @return the value of flea_user_original.create_time
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_user_original.create_time
     *
     * @param createTime the value for flea_user_original.create_time
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_user_original.update_time
     *
     * @return the value of flea_user_original.update_time
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_user_original.update_time
     *
     * @param updateTime the value for flea_user_original.update_time
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flea_user_original.status
     *
     * @return the value of flea_user_original.status
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flea_user_original.status
     *
     * @param status the value for flea_user_original.status
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}