package com.flea.dao;

import com.flea.pojo.UserOriginalInfo;

public interface UserOriginalInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flea_user_original
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flea_user_original
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    int insert(UserOriginalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flea_user_original
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    int insertSelective(UserOriginalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flea_user_original
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    UserOriginalInfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flea_user_original
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    int updateByPrimaryKeySelective(UserOriginalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flea_user_original
     *
     * @mbg.generated Wed Mar 13 23:41:43 CST 2019
     */
    int updateByPrimaryKey(UserOriginalInfo record);

    int checkPhoneNumber(String phoneNumber);

    UserOriginalInfo selectUserInfoByphoneNumberAndPassword(String phoneNumber, String password);
}